'use strict';
const assert = require('assert');
const fs = require('fs');
const html = fs.readFileSync('public/index.html', 'utf8');
const js = fs.readFileSync('public/report.js', 'utf8');
const slides = fs.readFileSync('public/report-slides.js', 'utf8');
const server = fs.readFileSync('server.js', 'utf8');

assert.match(html, /id="rpt-archive-btn"/, '个人报告标题栏应有周报档案入口');
assert.match(html, /id="rpt-archive-mask"/, '档案应使用可关闭的抽屉');
assert.match(js, /\/api\/reports\/personal\/archive\/create/, '前端应能创建周报归档');
assert.match(js, /\/api\/reports\/personal\/archive\/revision/, '前端应能创建历史修订版');
assert.match(js, /\/api\/reports\/personal\/archive\/official/, '前端应能设定正式版');
assert.match(js, /当前报告已还原为三个系统页/, '归档后应回到新的三页系统报告');
assert.match(js, /ReportSlides\.setPageActions\(\{ rename: openRenameSlide, delete: openDeleteSlide \}\)/, '自定义页页级操作应挂到正文编辑工具条');
assert.match(js, /archiveView \? new Date\(`\$\{archiveView\.weekStart\}T00:00:00`\)/, '历史 PDF 文件名应使用档案周');
assert.match(slides, /function setEditable\(value\)/, '正式档案应能让自定义页进入只读态');
assert.match(slides, /if \(presenting \|\| readOnly\) return/, '只读档案不应触发自定义页保存');
assert.doesNotMatch(server, /\|\| \(await reportNews\.summary\(me\.id\)\)\.news/, '归档不能回退使用其他周的 AI 新闻');
assert.match(js, /function openArchiveWindow\(weekStart, versionId, editable\)/, '查看档案必须有独立窗口入口');
assert.match(js, /window\.open\(archiveUrl\.toString\(\), '_blank', 'noopener'\)/, '查看档案必须在新窗口打开');
assert.match(js, /new URLSearchParams\(window\.location\.search\)/, '独立窗口必须从 URL 读取指定档案');
assert.match(js, /openArchive\(archiveWeek, archiveVersion, archiveEditable\)/, '独立窗口必须加载 URL 指定版本');
assert.doesNotMatch(js, /open\.onclick = \(\) => openArchive\(item\.weekStart, version\.id, false\)/, '主窗口查看不能覆盖实时报告');
assert.match(js, /function archivePeriodLabel\(weekStart\)/, '档案列表应将周一日期换算为 FY 季度周编号');
assert.match(js, /return `FY\$\{String\(year\)\.slice\(-2\)\} \$\{quarterWeek\}`/, '档案列表编号应沿用 FYxx QxWxx 口径');
assert.match(js, /archivePeriodLabel\(item\.weekStart\).*archiveLabel\(item\.weekStart\)/, '档案标题应同时显示周期编号和日期范围');
console.log('✓ report archive UI is wired for snapshot, revision, and weekly export');
